### ISSUE TITLE
GTX 1660TI (Not working with GPU ML.NET)

### ISSUE THREAD

**Issue by acensmar** [dotnet/machinelearning-modelbuilder#998]
### System information

- **Windows 10 1909**:
- **.NET Core 3.1**: 
- **Nvidia Geforce GTX 1660ti**: 
- **Amd Ryzen 5 2600 Six-core processor**: 

### Issue

- **I am not able to use the GPU (preview) option due to the error below.**
- **I am able to use the CPU option, but it's really slow!**
![errorcuda](https://user-images.githubusercontent.com/71263573/93080040-c4c49900-f695-11ea-9979-2811abda564f.png)

### Installed
cudnn-10.0-windows10-x64-v7.6.4.38 (copied bin file to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\)
cuda_10.0.130_win10
SciSharp.TensorFlow.Redist-Windows-GPU
ML.NET Model Builder (Preview) 16.2.0.2046002
ML.NET Model Builder GPU Support (Preview) 16.2.2046002

`Tried in both VS2019 preview, and VS2019 same outcome!`
`Tried with and without SciSharp.TensorFlow.Redist-Windows-GPU, same outcome!`
`Tried to build only as x64, same outcome!`
`Tried v7.6.4.38, v7.6.5.32, v7.6.3.30 cudnns, same outcome!`

### Driver
![driver](https://user-images.githubusercontent.com/71263573/93081492-00606280-f698-11ea-9e79-1ae72f41a117.png)

I updated my nvidia driver to 452.06 from 411.31 since I am using my PC from gaming and I had insane FPS drops. But I am confident that I had the same issue before hand!

### Source code / logs

|     Trainer                              MicroAccuracy  MacroAccuracy  Duration #Iteration                     |
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:00.0001582.
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed
**[Source=AutoML, Kind=Error] Pipeline crashed: xf=ValueToKeyMapping{ col=Label:Label} xf=RawByteImageLoading{ col=ImageSource_featurized:ImageSource imageFolder=} xf=ColumnCopying{ col=Features:ImageSource_featurized} tr=ImageClassification{} xf=KeyToValueMapping{ col=PredictedLabel:PredictedLabel} cache=- . Exception: Tensorflow.TensorflowException: 2 root error(s) found.**
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v2_50/conv1/Conv2D}}]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node resnet_v2_50/conv1/Conv2D}}]]
	 [[resnet_v2_50/SpatialSqueeze/_7]]
0 successful operations.
0 derived errors ignored.
   at Tensorflow.Status.Check(Boolean throwException)
   at Microsoft.ML.TensorFlow.TensorFlowUtils.Runner.Run()
   at Microsoft.ML.Vision.ImageClassificationTrainer.CacheFeaturizedImagesToDisk(IDataView input, String labelColumnName, String imageColumnName, ImageProcessor imageProcessor, String inputTensorName, String outputTensorName, String cacheFilePath, Dataset dataset, Action`1 metricsCallback, Nullable`1 validationFraction)
   at Microsoft.ML.Vision.ImageClassificationTrainer.TrainModelCore(TrainContext trainContext)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.RunnerUtil.TrainAndScorePipeline[TMetrics](MLContext context, SuggestedPipeline pipeline, IDataView trainData, IDataView validData, String groupId, String labelColumn, IMetricsAgent`1 metricsAgent, ITransformer preprocessorTransform, FileInfo modelFileInfo, DataViewSchema modelInputSchema, IChannel logger)
[Source=ImageClassificationTrainer; ImageClassificationTrainer, Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel started
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel finished. Elapsed 00:00:00.0002046.
[Source=ImageClassificationTrainer; Ensuring meta files are present., Kind=Trace] Channel disposed
Training cancelled

**Comment by JakeRadMSFT** [comment]
Hello @acensmar!
Sorry you're hitting this issue. Unfortunately it's a bit of an annoying process to get everything hooked up correctly. It's one of the main reasons GPU support was delayed so long.

Things to check:

- Ensure no other Cuda/CuDNN versions are installed on your machine. They can interfere with the path and cause the wrong version to be loaded.
- Make sure it's the versions of Cuda/CuDNN in these instructions: https://docs.microsoft.com/en-us/dotnet/machine-learning/how-to-guides/install-gpu-model-builder
- Make sure you're GPU drive is up to date. Unfortunately the CUDA installer will actually downgrade your GPU driver. Either uncheck install driver or update your driver from NVidia after installing CUDA.

Hopefully this helps! If it still doesn't work - please report back and we'll try to figure it out.

**Comment by fuomag9** [comment]
Same issue with a 2070S, this happens with tensorflow via python as well and it's fixed by enabling memory growth like this
```
import tensorflow as tf
def tf_fix(tf):
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if gpus:
        try:
            for gpu in gpus:
                tf.config.experimental.set_memory_growth(gpu, True)
        except RuntimeError as e:
            print(e)
tf_fix(tf)
```
I don't know any way to replicate this with this extension, and according to [this ](https://www.reddit.com/r/tensorflow/comments/f2hmu1/help_new_gpu_and_tensorflow_goes_lol_max_out_the/fhf4b5d?utm_source=share&utm_medium=web2x&context=3)comment on reddit it's a known issue with turing cards. Rebooting the system also fixes this without running code

**Comment by JakeRadMSFT** [comment]
@acensmar are you still hitting this issue?

**Comment by JakeRadMSFT** [comment]
Resolving for now @acensmar did a reboot happen to help? (Based on @fuomag9 's recommendation)

**Comment by fuomag9** [comment]
@JakeRadMSFT I don't think this can be marked as resolved unless memory growth is implemented during the automated training since I don't think rebooting the machine is a fix as the problem represents over time
